export const AXIOS_INSTANCE_TOKEN = 'AXIOS_INSTANCE_TOKEN';
export const AXIOS_RETRY_LIMIT = 'AXIOS_RETRY_LIMIT';
export const HTTP_STRATEGY_TOKEN = 'HTTP_STRATEGY_TOKEN';
export const HTTP_MODULE_OPTIONS = 'HTTP_MODULE_OPTIONS';
export const HTTP_ENVIRONMENT_TOKEN = 'HTTP_ENVIRONMENT_TOKEN';
export const TOKEN_EXPIRE_THRESHOLD_MS = 500;
