export const DISCORD_CLIENT = 'DISCORD_CLIENT';

export const DISCORD_COG = 'DISCORD_COG';
export const DISCORD_COG_GROUP = 'DISCORD_COG_GROUP';
export const DISCORD_COG_COMMAND = 'DISCORD_COG_COMMAND';

export const DISCORD_COMMAND_ID = 'DISCORD_COMMAND_ID';
export const DISCORD_COMMAND_NAME = 'DISCORD_COMMAND_NAME';
export const DISCORD_COMMAND_DESC = 'DISCORD_COMMAND_DESC';
export const DISCORD_COMMAND_ALIAS = 'DISCORD_COMMAND_ALIAS';
export const DISCORD_SUB_COMMAND = 'DISCORD_SUB_COMMAND';
export const DISCORD_EVENT = 'DISCORD_EVENT';
