/**
 * Discord Constants
 */

export const DISCORD_CLIENT = 'DISCORD_CLIENT';
export const DISCORD_PLUGIN = 'DISCORD_PLUGIN';
export const DISCORD_PLUGIN_COMMAND = 'DISCORD_PLUGIN_COMMAND';
export const DISCORD_PLUGIN_GROUP = 'DISCORD_PLUGIN_GROUP';
export const DISCORD_PLUGIN_LOOP = 'DISCORD_PLUGIN_LOOP';
export const DISCORD_PLUGIN_EVENT = 'DISCORD_PLUGIN_EVENT';

/**
 * Authentication
 */

export const ACCESS_CONTROL = 'ACCESS_CONTROL';
export const PERMISSION_METADATA = 'PERMISSION_METADATA';
